import{a as p,S as I,i as g}from"./assets/vendor-f144e563.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const S=15;async function L(e,r){p.defaults.baseURL="https://pixabay.com";const o={key:"44428976-d6e941eddcd51cc03234da6bf",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:r};try{return(await p.get("/api/",{params:o})).data}catch(i){console.log(i)}}document.getElementById("gallery");function b(e){return e.map(o=>`
        <li class="gallery-item">
            <a href="${o.largeImageURL}" class="gallery-link">
                <img src="${o.webformatURL}" alt="${o.tags}">
            </a>
            <div class="info">
                <p><strong>Likes:</strong> ${o.likes}</p>
                <p><strong>Views:</strong> ${o.views}</p>
                <p><strong>Comments:</strong> ${o.comments}</p>
                <p><strong>Downloads:</strong> ${o.downloads}</p>
            </div>
        </li>`).join("")}function v(e){e.classList.remove("loader-hidden")}function E(e){e.classList.add("loader-hidden")}const y=document.getElementById("search-form"),k=document.getElementById("search-input"),l=document.getElementById("loader"),d=document.querySelector(".gallery"),m=document.querySelector(".load-more__button");let w=new I(".gallery a",{captionsData:"alt",captionDelay:250});const M=15;let a=1,n="",h;function c(){d.innerHTML=""}function $(){return a=a+1}function f(){m.classList.remove("active")}function q(){m.classList.add("active")}function P(){return a=1}function B(){if(a>=h)return f(),g.error({class:"izt-toast-message",message:"We're sorry, but you've reached the end of search results.",messageSize:"16",messageLineHeight:"24",messageColor:"#ffffff",backgroundColor:"#b51b1b",position:"topRight",theme:"dark"});q()}function O(){const r=d.children[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}y.addEventListener("submit",async e=>{if(e.preventDefault(),n=k.value.trim(),n===""||n===!n){c(),f(),g.error({title:"Error",message:"Search query cannot be empty!"});return}if(P(),f(),n.length!==0){v(l);try{const r=await L(n,a);if(h=Math.ceil(r.totalHits/M),r.hits.length===0)c(),g.show({class:"izt-toast-message",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16",messageLineHeight:"24",messageColor:"#ffffff",backgroundColor:"#b51b1b",position:"topRight",theme:"dark"}),c();else{c();const o=b(r.hits);d.innerHTML=o,w.refresh(),B()}}catch(r){console.log(r)}E(l)}y.reset()});m.addEventListener("click",async()=>{$();try{const e=await L(n,a);v(l),d.insertAdjacentHTML("beforeend",b(e.hits)),w.refresh(),O(),E(l),B(h)}catch(e){console.log(e)}});
//# sourceMappingURL=commonHelpers.js.map
