import{a as m,S,i as u}from"./assets/vendor-f144e563.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function L(e,r){m.defaults.baseURL="https://pixabay.com";const o={key:"44428976-d6e941eddcd51cc03234da6bf",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:r};try{return(await m.get("/api/",{params:o})).data}catch(i){console.log(i)}}document.getElementById("gallery");function b(e){return e.map(o=>`
        <li class="gallery-item">
            <a href="${o.largeImageURL}" class="gallery-link">
                <img src="${o.webformatURL}" alt="${o.tags}">
            </a>
            <div class="info">
                <p><strong>Likes:</strong> ${o.likes}</p>
                <p><strong>Views:</strong> ${o.views}</p>
                <p><strong>Comments:</strong> ${o.comments}</p>
                <p><strong>Downloads:</strong> ${o.downloads}</p>
            </div>
        </li>`).join("")}function v(e){e.classList.remove("loader-hidden")}function E(e){e.classList.add("loader-hidden")}const h=document.getElementById("search-form"),k=document.getElementById("search-input"),c=document.getElementById("loader"),l=document.querySelector(".gallery"),f=document.querySelector(".load-more__button");let w=new S(".gallery a",{captionsData:"alt",captionDelay:250});const P=15;let a=1,n="",g;function p(){l.innerHTML=""}function y(){return a=a+1}function B(){f.classList.remove("active")}function M(){f.classList.add("active")}function q(){return a=1}function I(){if(a>=g)return B(),u.error({class:"izt-toast-message",message:"We're sorry, but you've reached the end of search results.",messageSize:"16",messageLineHeight:"24",messageColor:"#ffffff",backgroundColor:"#b51b1b",position:"topRight",theme:"dark"});M()}function C(){const r=l.children[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}h.addEventListener("submit",async e=>{if(e.preventDefault(),n=k.value.trim(),n===""||n===!n){u.error({title:"Error",message:"Search query cannot be empty!"});return}if(q(),B(),n.length!==0){v(c);try{const r=await L(n,a);if(g=Math.ceil(r.totalHits/P),r.hits.length===0)u.show({class:"izt-toast-message",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16",messageLineHeight:"24",messageColor:"#ffffff",backgroundColor:"#b51b1b",iconUrl:iconClose,position:"topRight",theme:"dark"}),p();else{p();const o=b(r.hits);l.innerHTML=o,w.refresh(),I()}}catch(r){console.log(r)}E(c)}h.reset()});f.addEventListener("click",async()=>{y();try{const e=await L(n,a);v(c),l.insertAdjacentHTML("beforeend",b(e.hits)),w.refresh(),C(),E(c),y(),I(g)}catch(e){console.log(e)}});
//# sourceMappingURL=commonHelpers.js.map
